# Generated by Django 3.1.1 on 2020-09-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.TextField(max_length=80),
        ),
    ]
