# Generated by Django 3.1.1 on 2020-09-24 07:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200924_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title2',
        ),
        migrations.AddField(
            model_name='task',
            name='label2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LABEL 1', 'LABEL 1'), ('LABEL 2', 'LABEL 2'), ('LABEL 3', 'LABEL 3'), ('LABEL 4', 'LABEL 4')], max_length=31),
        ),
    ]
