# Generated by Django 3.0.5 on 2020-09-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200924_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title2',
        ),
    ]
