# Generated by Django 3.1.1 on 2020-09-24 08:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200924_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'LABEL 1'), ('2', 'LABEL 2'), ('3', 'LABEL 3'), ('4', 'LABEL 4')], max_length=7),
        ),
    ]
